apiVersion: v1
kind: Service
metadata:
  name: depi-app-service
  namespace: depi-app-namespace  # Specify the namespace here
spec:
  type: LoadBalancer
  selector:
    app: depi-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
